data_source:
    groups_desc: data/small_group_description.csv
    train_x: data/transactions_train.csv
    test_x: data/transactions_test.csv
    train_target: data/train_target.csv
    test_target: data/test.csv
global_features:
    train_set: data/global_features/train_features.npy
    valid_set: data/global_features/valid_features.npy
ts_features:
    train_set:
        small_group_seq: data/ts_max_features/train_groups.npy
        money_seq: data/ts_max_features/train_money_seq.npy
    valid_set:
        small_group_seq: data/ts_max_features/valid_groups.npy
        money_seq: data/ts_max_features/valid_money_seq.npy
lgbm_params:
    n_estimators: 300
    max_depth: 8
    learning_rate: 0.05
    num_leaves: 31
    class_weight: 'balanced'
    random_state: 42
    seed: 58
    bagging_seed: 3
    feature_fraction_seed: 2
    data_random_seed: 1
    verbose: -1
    silent: True
